import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { GetSessionParams, getSession } from "next-auth/react";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import { Toaster } from "react-hot-toast";
import Widget from "../components/Widget";

type HomeProps = {
  session: GetSessionParams;
};

const Home: NextPage<HomeProps> = ({ session }) => {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Toaster
        toastOptions={{
          className: "text-md",
          style: {
            color: "#713200",
          },
        }}
      />

      <Header />
      <main className="flex bg-gray-100">
        <Sidebar />
        <Feed />
        <Widget />
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
